# Generated by Django 5.2.11 on 2026-03-02 14:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Pack Étudiant, Pack Pro IA', max_length=100)),
                ('prix', models.PositiveIntegerField(help_text='Montant en devise locale (ex: FCFA)')),
                ('duree_jours', models.IntegerField(default=30)),
                ('can_access_videos', models.BooleanField(default=True)),
                ('can_access_books', models.BooleanField(default=True)),
                ('can_use_ai_chat', models.BooleanField(default=False)),
                ('storage_limit_mb', models.FloatField(default=0.0, help_text='Limite de stockage PDF en Mo')),
            ],
            options={
                'verbose_name': "Offre d'Abonnement",
                'verbose_name_plural': "Offres d'Abonnement",
            },
        ),
        migrations.CreateModel(
            name='PaysAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_iso', django_countries.fields.CountryField(help_text="Sélectionnez le pays (ex: Congo, Côte d'Ivoire)", max_length=2, unique=True)),
                ('indicatif', models.CharField(help_text='Ex: +242', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver les paiements dans ce pays')),
            ],
            options={
                'verbose_name': 'Pays Autorisé',
                'verbose_name_plural': 'Pays Autorisés',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fichier_video', models.FileField(upload_to='videos_privees/')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='thumbs/')),
                ('is_free', models.BooleanField(default=False, help_text='Cocher pour offrir cette vidéo gratuitement (Marketing)')),
                ('date_publication', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telephone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('premium_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='core.paysautorise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier_pdf', models.FileField(upload_to='docs_ia_prives/')),
                ('taille_mb', models.FloatField(default=0.0)),
                ('vector_id', models.CharField(blank=True, help_text='ID dans la base vectorielle (Pinecone/Chroma)', max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(db_index=True)),
                ('actif', models.BooleanField(default=True, help_text='Peut être désactivé manuellement par un admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offreabonnement')),
            ],
            options={
                'verbose_name': 'Historique Abonnement',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id_interne', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference_operateur', models.CharField(blank=True, db_index=True, help_text='ID MTN/Orange', max_length=100, null=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='PENDING', max_length=20)),
                ('montant_paye', models.PositiveIntegerField()),
                ('reponse_api_brute', models.TextField(blank=True, help_text="JSON de l'agrégateur de paiement", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.offreabonnement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
