# Generated by Django 5.2.11 on 2026-03-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commentaire_like_profile_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie (ex: Grammaire, Conjugaison)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description courte de la catégorie')),
                ('couleur', models.CharField(default='#3B82F6', help_text="Code couleur hex pour l'affichage (ex: #3B82F6)", max_length=7)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône ou lettre initiale", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour masquer la catégorie')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (croissant)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer la vidéo'),
        ),
        migrations.AddField(
            model_name='video',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.categorie'),
        ),
    ]
