# Generated by Django 5.2.11 on 2026-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categorie_video_is_active_video_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='customer_external_id',
            field=models.CharField(blank=True, help_text='ID client dans le système', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, help_text='Date de confirmation du paiement', null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_phone_number',
            field=models.CharField(blank=True, help_text='Numéro ayant servi au paiement', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('MOOV', 'Moov Money')], default='MTN', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='webhook_signature',
            field=models.CharField(blank=True, help_text='Signature du webhook', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_operateur',
            field=models.CharField(blank=True, db_index=True, help_text='ID OpenPay (ex: PTXN26042237B99A5D9)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reponse_api_brute',
            field=models.TextField(blank=True, help_text='JSON de la réponse OpenPay', null=True),
        ),
    ]
