# Generated by Django 5.2.11 on 2026-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paiement_options_paiement_customer_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='expire_a',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration du lien de paiement", null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Lien de paiement OpenPay (PayLink)', null=True),
        ),
    ]
