# Generated by Django 5.2.11 on 2026-03-11 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paiement_expire_a_paiement_payment_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Évite le traitement en double des webhooks'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='payment_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token de paiement OpenPay', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['payment_token'], name='core_paieme_payment_4adc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference_operateur'], name='core_paieme_referen_d21913_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['is_processed', 'statut'], name='core_paieme_is_proc_bb7a70_idx'),
        ),
    ]
