# Generated by Django 6.0.3 on 2026-03-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paiement_is_processed_paiement_payment_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offreabonnement',
            options={'ordering': ['prix'], 'verbose_name': "Offre d'Abonnement", 'verbose_name_plural': "Offres d'Abonnement"},
        ),
        migrations.AddField(
            model_name='offreabonnement',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Décocher pour masquer l'offre"),
        ),
    ]
