# Generated by Django 6.0.3 on 2026-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_offreabonnement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreabonnement',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Cocher pour afficher le badge 'Recommandé' sur cette offre"),
        ),
        migrations.AddField(
            model_name='offreabonnement',
            name='specificites',
            field=models.JSONField(blank=True, default=list, help_text="Liste des spécificités de l'offre (une par ligne)"),
        ),
    ]
