# Generated by Django 6.0.3 on 2026-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_offreabonnement_is_recommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offreabonnement',
            name='specificites',
            field=models.TextField(blank=True, help_text='Une spécificité par ligne'),
        ),
    ]
